### ISSUE TITLE
[Question]: Change icon color

### ISSUE THREAD

**Issue by dieuvolkanos** [junalmeida/homeassistant-minimalistic-area-card#102]
### What happened?

Hi,

I tried to change sensor icon color in the card without success. Someone have a solution?

Thanks

### Card Version

1.2.0

### HomeAssistant Version

2024.6.3

**Comment by Nurgus** [comment]
What did you try? 

I don't think this is possible at the moment although I'd really like to see it. Being able to set the colour of each icon in a template would be really useful.

**Comment by oerix** [comment]
Seems this repo and other forks are dead, I wouldn't get my hopes up with any new developments unfortunately.

**Comment by dieuvolkanos** [comment]
> What did you try?
> 
> I don't think this is possible at the moment although I'd really like to see it. Being able to set the colour of each icon in a template would be really useful.

I have 2 sensor (recycle bin and garbage can) in the same card. I want to put one in green and other one in brown. 

I will check template to change the icon colors.

**Comment by LesTR** [comment]
@dieuvolkanos yep, that's not possible right now. You can just enable/disable color by setting `state_color` value, but [looks like](https://github.com/home-assistant/frontend/blob/dev/src/components/entity/state-badge.ts#L39) it should not be so hard to add support for this.

I already opened a PR that adds support for overriding the icon (see https://github.com/junalmeida/homeassistant-minimalistic-area-card/pull/103), it should be simple to do that.

It should look like:
```
- entity: binary_sensor.main_door_opening
  icon: mdi:door
  state_color: true
  state:
    - value: 'on'
      icon: mdi:door-open
      color: green
    - value: 'off'
      icon: mdi:door-closed
      color: red
```  

WDYT? cc @junalmeida
