### ISSUE TITLE
[Question]: Font Size

### ISSUE THREAD

**Issue by templeowls21** [junalmeida/homeassistant-minimalistic-area-card#111]
### What happened?

Is there any way to change the font size of the "area" header?

### Card Version

1.2.0

### HomeAssistant Version

13.2

**Comment by LesTR** [comment]
You can use [card-mod](https://github.com/thomasloven/lovelace-card-mod) plugin for this.
Something like:
```yaml
card_mod:
  style: |
    .box .card-header {
      font-size: 2em !important;
    }
```
