### ISSUE TITLE
[Bug]: Small sensor icons, and the highlight is misaligned

### ISSUE THREAD

**Issue by TomHart** [junalmeida/homeassistant-minimalistic-area-card#114]
### What happened?

Zoomed in
<img width="160" alt="Image" src="https://github.com/user-attachments/assets/0cc20153-e0f2-41d0-9426-49efcfada133" />

Real size
<img width="80" alt="Image" src="https://github.com/user-attachments/assets/0cc20153-e0f2-41d0-9426-49efcfada133" />

The icons used to be larger, and the highlight is misaligned with the icon. It'd be great if it'd be possible to specify the size for the icons 

### Card Version

1.2.0

### Home Assistant Version

2025.1.2

### Browser Version

Firefox 134

### Relevant javascript log output

```shell

```

**Comment by junalmeida** [comment]
Information icons that are positioned on top-left are supposed to be small (because there is no actions on them). 
Action icons positioned on bottom-right are bigger because you can tap/click on them. 

Make sure the class of your entities are supported with an action, not information.

![Image](https://github.com/user-attachments/assets/eec1bc95-1bb0-4cb9-9883-48fbaf975f28)

**Comment by TomHart** [comment]
I have 2 `binary_sensors` there that I want to do something on tap, can I tell it to put them in the bottom?

```yaml
  - entity: binary_sensor.tv_on
    tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.toggle_living_room_tv_sky
  - entity: binary_sensor.living_room_lights_on
    tap_action:
      action: call-service
      service: automation.trigger
      service_data:
        entity_id: automation.toggle_number_between_0_and_3
```
