### ISSUE TITLE
Ability to turn off popups on sensors

### ISSUE THREAD

**Issue by seraphx2** [junalmeida/homeassistant-minimalistic-area-card#14]
I don't personally have a need to see the built-in HA popup for the sensors in the binary row.

It cause me to have to be more specific where I touch the card for navigation.

A toggle to turn that feature off would be nice.

**Comment by junalmeida** [comment]
I believe what you want if already there, just not explicitly documented. You can try specify a `tap_action` for an entity, like: 

```
 - type: custom:minimalistic-area-card
   title: Living Room
   image: /local/img/living-room.jpg #any image file on /config/www or an absolute image url
   tap_action:
      action: navigate
      navigation_path: /lovelace/living-room
   entities:
      - entity: media_player.living_room_tv
         tap_action: 
            action: none
```
See more: https://www.home-assistant.io/dashboards/actions/

Let me know if that works for you

**Comment by seraphx2** [comment]
yeah. that helps.

**Comment by seraphx2** [comment]
once i eliminated the text triggering the popup from a tap, i found a problem. the icons themselves are also tied into a hold action and when i do that, it also brings up the HA popup..... is there a way to turn that off?

**Comment by junalmeida** [comment]
```
   entities:
      - entity: media_player.living_room_tv
         tap_action: 
            action: none
         hold_action: 
            action: none
``` 

All actions defined on https://www.home-assistant.io/dashboards/actions/ are supported, let me know if this doesn't work for you.

Regarding the "click area" I can't really change it because I'm using the icon component from home assistant and that click area is defined by the component.
