### ISSUE TITLE
Entity optioned don’t work, icon and State-Color

### ISSUE THREAD

**Issue by superpower10** [junalmeida/homeassistant-minimalistic-area-card#19]
**Is your feature request related to a problem? Please describe.**
This card is supposed to show the state of the sensors, switches and lights. But if the color is hardly different from the off state, it doesn’t serve its purpose.

**Describe the solution you'd like**
1. Lamps: Color the icon if turned on according to its actual color or let user set the color of it. 
2. Entity options as described in the “Options” of the description don’t work (e.g. icon in front of text and state_color)
3. Picture for the card other than kitchen would be great

**Comment by junalmeida** [comment]
1. Have you tried to color the entity based on its state using "custom-ui" templates? The good pro with this approach is that your template would be valid across all HA cards and info-dialogs.
2. Does your options works if you add a native "entities" card? Could you please share yamls of both minimalistic-card and regular entities card with options set and a screenshot?
3. I'm not sure I got your idea right. On the current version you can specify any jpg/png image url for the card image.

**Comment by jlaska** [comment]
Picking this back up as I'm experiencing the issue in the latest release still. 

> * Have you tried to color the entity based on its state using "custom-ui" templates? The good pro with this approach is that your template would be valid across all HA cards and info-dialogs.

@junalmeida I haven't tried that ... are you suggesting using [lovelace-card-mod](https://github.com/thomasloven/lovelace-)?

> * Does your options works if you add a native "entities" card? Could you please share yamls of both minimalistic-card and regular entities card with options set and a screenshot?

Sure, please refer to below.  The two examples show how `state_color` is handled differently in the `minimalistic-area-card` and the `entities` cards.

```yaml
type: custom:minimalistic-area-card
title: Minimalistic Area Card
background_color: darkblue
entities:
  - entity: light.bedroom_lamps_zha_group_0x0002
    name: Lamps
    state_color: true
    tap_action:
      action: more-info
  - entity: group.bedroom_lights
    name: Lights
    state_color: true
    tap_action:
      action: more-info
  - entity: fan.bedroom_fan
    name: Fan
    state_color: true
```

```yaml
title: Entities Card
type: entities
entities:
  - entity: light.bedroom_lamps_zha_group_0x0002
    name: Lamps
    state_color: true
  - entity: group.bedroom_lights
    name: All Lights
    state_color: true
  - entity: fan.bedroom_fan
    name: fan
    state_color: true
```

![image](https://user-images.githubusercontent.com/1051173/199042118-00d0c71b-b79f-41b4-927a-592c9d8d0fb5.png)
