### ISSUE TITLE
[Bug]: Unable to call service

### ISSUE THREAD

**Issue by SKis274** [junalmeida/homeassistant-minimalistic-area-card#25]
### What happened?

Hi there,

I'm trying to call a service inside the area-card. Here is an example.

```
type: custom:minimalistic-area-card
title: Esszimmer
image: >-
  image/serve/5514b9769af14cdd146c0946070c0a05/512x512
background_color: null
tap_action:
  action: navigate
  navigation_path: /lovelace-mushroom/dinner-room
state_color: true
entities:
  - entity: sensor.klimaanlage_esszimmer_temperature
  - entity: sensor.klimaanlage_esszimmer_humidity
  - entity: vacuum.puck_3_0_eg
    tap_action:
      action: call-service
      confirmation:
        text: Soll das Esszimmer jetzt gereinigt werden?
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.puck_3_0_eg
      data:
        segments: 17
```

After the confirmation the following error occurs:
Fehler beim Aufrufen des Diensts xiaomi_miio/vacuum_clean_segment. required key not provided @ data['segments']

The service is correct, it works perfect with a pure entities card like this with the same formatting:

```
type: entities
entities:
  - entity: vacuum.puck_3_0_eg
    tap_action:
      action: call-service
      confirmation:
        text: Soll das Esszimmer jetzt gereinigt werden?
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.puck_3_0_eg
      data:
        segments: 17
```

Any idea why it doesn't work? Thanks a lot :-)

### Card Version

1.0.6

### HomeAssistant Version

2022.10.2
