### ISSUE TITLE
[Bug]: Background image does not respect rounded corners

### ISSUE THREAD

**Issue by laszlojakab** [junalmeida/homeassistant-minimalistic-area-card#31]
### What happened?

If you set a background image the card does not respect the rounded corners, see image below:

![image](https://user-images.githubusercontent.com/6196882/209411573-360b1582-c185-4066-a143-c94cc2cbe4f1.png)

I think the design should be the same with or without background image.

### Card Version

1.1.2

### HomeAssistant Version

2022.12.8

**Comment by laszlojakab** [comment]
As I see an  `overflow: hidden` shoud be added to `ha-card` element to solve the problem.

**Comment by junalmeida** [comment]
That's interesting because this does not happen here: 
![image](https://user-images.githubusercontent.com/991675/209850828-db462e3c-1fc7-43db-b9a5-9e877c018506.png)

I wonder if you may be using an outdated version or a not common browser?

**Comment by laszlojakab** [comment]
I have prepared an other example:

![image](https://user-images.githubusercontent.com/6196882/209916063-78353914-33b0-4543-9894-66411c8042da.png)

The code to reproduce:

```yaml
type: vertical-stack
cards:
- type: custom:minimalistic-area-card
  title: Room with background
  area: working_room
  image: >-
    https://www.thespruce.com/thmb/kNPU_doz6IvtUXrtV1GnzI85BXs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/living-room-ideas-5194639-hero-a99a77f61b9b4e368c62ca603ab45322.jpg
  entities:
    - light.dining_room_led_light
    - sensor.dining_room_temperature
- type: custom:minimalistic-area-card
  title: Room without background
  area: working_room
  entities:
    - light.dining_room_led_light
    - sensor.dining_room_temperature

```

I'm using `Chrome 108.0.5359.125 (64 bites) (cohort: Stable)` from Windows 10. But from Android phone it looks like the same:

![image](https://user-images.githubusercontent.com/6196882/209916486-bf6511a0-667c-44d2-b439-2b7460cb77d2.png)
