### ISSUE TITLE
[Question]: Correctly styling ha-state-icon elements

### ISSUE THREAD

**Issue by jlaska** [junalmeida/homeassistant-minimalistic-area-card#45]
### What happened?

Thank you for this fantastic card!  I do some customization of the entity icons using [card_mod](https://github.com/thomasloven/lovelace-card-mod).  

I'm able to animate my fan entities by modifying the `state-badge` element, as follows:
```yaml
    type: custom:minimalistic-area-card
    title: 'Testing'
    card_mod:
      style:
        .: |
          @keyframes spin {
            0% {
              transform: rotate(0deg);
            }
            100% {
              transform: rotate(359deg);
            }
          }
          .box ha-icon-button.state-on state-badge[title*='fan' i] {
            animation: spin 1.5s infinite linear;                                                                                                                     
          }
```

However, I'd prefer to access the `ha-state-icon` elements directly, but I'm not able to get this to work.

```yaml
    type: custom:minimalistic-area-card
    title: 'Testing'
    card_mod:
      style:
          @keyframes spin {
            0% {
              transform: rotate(0deg);
            }
            100% {
              transform: rotate(359deg);
            }
          }
        ha-state-icon$: |
          :host([data-domain=fan][data-state=on]) {
            animation: spin 1.5s infinite linear;
          }                                                                                                                                                           
```

Any guidance/thoughts/feedback is appreciated! 

### Card Version

1.1.8

### HomeAssistant Version

2023.1.0 (Frontend: 20230104.0)
