### ISSUE TITLE
Possibility to change icon of an entity

### ISSUE THREAD

**Issue by philo2** [junalmeida/homeassistant-minimalistic-area-card#5]
**Describe the solution you'd like**
In the YAML, it would be nice to bypass the default icon of an entity to set a new one.

```
type: custom:minimalistic-area-card
title: Cuisine
image: https://demo.home-assistant.io/stub_config/kitchen.png
entities:
  - light.lumieres_cuisine
    icon: mdi:home-assistant
  - entity: input_select.mode
    icon: mdi:home
```

**Comment by junalmeida** [comment]
I will think about it. 
In the meanwhile you may use this: https://www.home-assistant.io/docs/configuration/customizing-devices/
Let me know if this makes sense on your scenario.

**Comment by junalmeida** [comment]
It seems you can already do this using the exact yaml you provided in this ticket:
```
entities:
  - entity: light.lumieres_cuisine
    icon: mdi:home-assistant
  - entity: input_select.mode
    icon: mdi:home
``` 
Let me know if this does not work for you.
