### ISSUE TITLE
[Question]:  use greyscale when main entity is off

### ISSUE THREAD

**Issue by Mariusthvdb** [junalmeida/homeassistant-minimalistic-area-card#53]
### What happened?

currently using a more complex set of custom:button-card configs for my Rooms, as shortcuts to those, I am in need of an option to the entities on the card, like you provide. So thats awesome and very nice indeed.

the one thing I would like to ask is whether you could add something along the lines of:

```
    entity_picture:
      - filter: >
          [[[ if (entity.state == 'off' || entity.state == 'unavailable') return 'grayscale(100%)';
              return 'grayscale(0%)'; ]]]
```

which is what I use currently on my button-cards, with obvious effect: entity == off, card is grey, entity == on, card is colored.

I can set a card_mod styling:

```
        - type: custom:minimalistic-area-card
          card_mod:
            style: |
              ha-card {
                filter: grayscale(100%);
              }
```

that actually works, and I can ofc template that to based on any state in HA. It would however need verbose mentioning of that entity, and could benefit from a 'main' entity on the card. so we could use the template I showed above.

thanks for considering!

### Card Version

1.1.8

### HomeAssistant Version

2023.2

### Relevant log output

```shell
not issues, so no log.
```

**Comment by junalmeida** [comment]
Unless I didn't understand your idea correctly, I don't think this aligns with the purpose of this card, as it is supposed to be related to an area, not any entity, even if you have only one entity on a said area.

**Comment by Mariusthvdb** [comment]
thx.
Ofc this crd is related to Area, and I use it like that, sure.
However, many Areas (can) have a 'main' entity, think a light, or switch, maybe even a binary_motion sensor. User configurable ofc would be my idea.
it would leverage the Area card in a way, that one could get the feedback right away, on that entity.


like so:

Attic area card:
off:
<img width="330" alt="Scherm­afbeelding 2023-01-30 om 21 41 39" src="https://user-images.githubusercontent.com/33354141/215590423-b47d92a6-83b8-45a4-b6ac-5226a428f4a3.png">

on:
<img width="334" alt="Scherm­afbeelding 2023-01-30 om 21 41 58" src="https://user-images.githubusercontent.com/33354141/215590473-b7d1eb37-6b92-4236-b25e-82f57f33f76d.png">

in blue there's a tooltip, so nevermind that...

**Comment by Mariusthvdb** [comment]
this is what I managed to do:
```
        - type: custom:minimalistic-area-card
          card_mod:
            style: |
              ha-card {
                filter: {{'grayscale(0%)' if is_state('light.laundry_ceiling','on')
                          else 'grayscale(100%)'}};
              }
#           title: Laundry
          image: /local/images/areas/bijkeuken_klein.jpg #any image file on /config/www or an absolute image url. optional, it uses area image if area is specified. (optional)
          area: bijkeuken # area id of an existing area defined in HA. (optional)
  #         background_color: yellow # a color name, rgb hex or rgba function when an image is not provided (optional)
#           camera_image: camera.bijkeuken # a camera entity to use as background (optional)
#           camera_view: 'auto' # auto, live (optional)
          shadow: false # Draws a drop shadow on icons (optional)
          hide_unavailable: false # Hide unavailable entities (optional)
          tap_action:
            action: navigate
            navigation_path: /ui-sub-views/bijkeuken
          hold_action:
            action: call-service
            service: light.toggle
            service_data:
              entity_id: light.laundry_ceiling
          entities: #optional, lists area entities automatically if ommited.
            - entity: sensor.laundry_sensor_temperature
```

and Ive set the `filter: brightness(1)` in an edited resource

allows to show the colored/greyed image used on the state. which is also used on the hold action.

if a main entity could be added:

        - type: custom:minimalistic-area-card
          card_mod:
            style: |
              ha-card {
                filter: {{'grayscale(0%)' if is_state(config.entity,'on')
                          else 'grayscale(100%)'}};
              }
#           title: Laundry
          image: /local/images/areas/bijkeuken_klein.jpg #any image file on /config/www or an absolute image url. optional, it uses area image if area is specified. (optional)
          area: bijkeuken # area id of an existing area defined in HA. (optional)
  #         background_color: yellow # a color name, rgb hex or rgba function when an image is not provided (optional)
#           camera_image: camera.bijkeuken # a camera entity to use as background (optional)
#           camera_view: 'auto' # auto, live (optional)
          shadow: false # Draws a drop shadow on icons (optional)
          hide_unavailable: false # Hide unavailable entities (optional)
          tap_action:
            action: navigate
            navigation_path: /ui-sub-views/bijkeuken
          hold_action:
            action: toggle
#            service: light.toggle
#            service_data:
#              entity_id: light.laundry_ceiling
          entities: #optional, lists area entities automatically if ommited.
            - entity: sensor.laundry_sensor_temperature

making that way easier to throw in the in a decluttering template ;-)
