### ISSUE TITLE
[Question]: the button is not activated from the card

### ISSUE THREAD

**Issue by bugavka** [junalmeida/homeassistant-minimalistic-area-card#58]
### What happened?

its properties appear and there is an opportunity to push
would like to click directly from the card

### Card Version

 v1.1.8

### HomeAssistant Version

2023.2.5

**Comment by junalmeida** [comment]
Not sure I got your problem. Could you please elaborate more? What properties? opportunity to push what? What is the entity kind? What are you trying to do?

**Comment by bugavka** [comment]
sorry for my english
entity - button
![image](https://user-images.githubusercontent.com/20883365/220385696-034893c8-2dc0-4425-a145-e562ab0088b5.png)
when you press on it
![image](https://user-images.githubusercontent.com/20883365/220386144-b4ff38cd-cea2-47d1-b874-8b176de14677.png)
not action

**Comment by bugavka** [comment]
it's not a problem, it's a suggestion. so that when you click on the entity button, it behaves like an entity switch

**Comment by junalmeida** [comment]
It seems this is a sensor and as far as I know, that's the default action of sensors in home assistant. If you want a different action, you can manually specify it. Take a look at https://www.home-assistant.io/dashboards/actions/
The `tap_action` property is allowed under the entity item in the list. 

It should be something like 

```yaml
entities:
  - entity: sensor.my_sensor
     tap_action: ...
     hold_action: ....
```

**Comment by RagingRoosevelt** [comment]
For anyone that stumbles on thin in the future, or for @bugavka:

I got it to work with the following:

```yaml
    tap_action:
      action: call-service
      service: button.press
      service_data: {}
      target:
        entity_id: button.my_button_id
```
