### ISSUE TITLE
[Question]: Double the size of the card

### ISSUE THREAD

**Issue by novus84** [junalmeida/homeassistant-minimalistic-area-card#60]
### What happened?

Hello,

the cards are really very useful and look great. 

is it possible to double the size of the card? 
I think then you could display the whole thing a little better and you would also have a better use of the webcam picture. 

### Card Version

1.4.1

### HomeAssistant Version

latest

**Comment by matrixx567** [comment]
Hi,

I'm using the [cardmod](https://github.com/thomasloven/lovelace-card-mod) to change the height of the card

```yaml
type: custom:mod-card
card:
  type: custom:minimalistic-area-card
  title: Livingroom
  image: /local/livingroom-banner.jpg
  tap_action:
    action: navigate
    navigation_path: /my-home/livingroom
  entities:
    - entity: sensor.tempsensor_temperature
      tap_action: none
      double_tap_action: none
      hold_action: none
card_mod:
  style: |
    ha-card {
      height: 120px;
    }
```
