### ISSUE TITLE
[Bug]: Mouse Cursor on entity icon behaves wrong

### ISSUE THREAD

**Issue by matrixx567** [junalmeida/homeassistant-minimalistic-area-card#77]
### What happened?

Hi,

Thanks for this great card. I'm using the Minimalistic-Area-Card as a navigation card. So if I click on the card it will be redirect to the appropriated dashboard. Therefore I've deactivated the interaction of all shown entities (like temperature) using the configuration below by setting the actions to `none`.

Current behavior:
The cursor correctly acts on the temperatue value by keeping the pointer:
![image](https://user-images.githubusercontent.com/4608946/233071394-b283e952-7df4-4b79-aac8-314ecd633794.png)

But if I place the cursor over the icon the pointer changes and the navigation of card doesn't work.
![image](https://user-images.githubusercontent.com/4608946/233071431-fd7f61a7-a8a8-4d3c-9cc8-8cd8c51c51c5.png)

Expected behavior:
The cursor shouldn't change the pointer and the navigation of the card should also work if I click on the icon of an entity.

Configuration of the card

```yaml
  - type: custom:minimalistic-area-card
    title: Wohnzimmer
    image: /local/livingroom-banner.jpg
    hide_unavailable: false
    shadow: true
    tap_action:
      action: navigate
      navigation_path: /my-home/livingroom
    entities:
      - entity: sensor.tempsensor_livingroom_1_temperature
        tap_action: none
        double_tap_action: none
        hold_action: none
      - entity: sensor.tempsensor_livingroom_1_humidity
        tap_action: none
        double_tap_action: none
        hold_action: none
      - entity: binary_sensor.windowsensor_livingroom_group
        tap_action: none
        double_tap_action: none
        hold_action: none
    card_mod:
      style: |
        :host {
          height: 120px;
        }
```

### Card Version

1.1.16

### Home Assistant Version

2023.4.5

### Browser Version

Chrome
