### ISSUE TITLE
[Bug]: Why the value of this template sensor is on newline

### ISSUE THREAD

**Issue by Rihan9** [junalmeida/homeassistant-minimalistic-area-card#83]
### What happened?

I think this image speak better than 100 words:
![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/33684020/0a2a5d02-5e33-4d0b-b8e9-c0e40fe601a8)

Code:

```
type: custom:minimalistic-area-card
title: Studio
area: sudio
hide_unavailable: false
tap_action:
  action: navigate
  navigation_path: /lovelace/sudio
entities:
  - light.luce_studio
  - sensor.sensore_clima_studio_temperature
  - sensor.sensore_clima_studio_humidity
  - sensor.thermalcomfort_studio_icona
```

### Card Version

1.1.16

### Home Assistant Version

2023.9.0

### Browser Version

Edge, latest
