### ISSUE TITLE
[Bug]: unable to call service to turn a scene on

### ISSUE THREAD

**Issue by DetunizedGravity** [junalmeida/homeassistant-minimalistic-area-card#85]
### What happened?

Hello, 
I created a minimalistic area card as a way to easily group status information and common actions in my living room. To begin with I wanted to be able to display climate information, toggle two light groups and turn on "lighting scenes".

Turns out I cannot turn a scene on from the card:
```
type: custom:minimalistic-area-card
title: Salon
area: Salon
hide_unavailable: false
tap_action:
  action: navigate
  navigation_path: /config/areas/area/salon
entities:
  - entity: light.plafonnier
  - entity: light.baie_vitree
  - entity: scene.soiree_tele
    tap_action:
      action: call_service
      service: scene.turn_on
      data:
        entity_id: scene.soiree_tele
```

With this I expect to see the icon I choosed when defining the scene to appear, and the scene to be turned on when I click this icon.

The first two entities work fine. The icon for the scene does appear, but clicking on it has no effect. I tried other syntaxes by replacing "data:" with "service_data:" and "target:" as found in other examples of service calls inside HA, but it did not work. The above syntax does work in the developpers tool.

This may be related to issue #25.

Best regards,
  Xavier

### Card Version

1.1.16

### Home Assistant Version

HA OS 11.1 Core 2023.10.5 

### Browser Version

Firefox 118.0.2 (64 bits) on Win10 22H2 build 19045.3570

**Comment by bauchschuss** [comment]
I know this issue is a little bit old but i had the same problem which i was able to solve now.
The way it is working for me looks the following:

```
type: custom:minimalistic-area-card
title: Schlafzimmer
image: >-
  https://media.moebelix.com/i/moebelix/PIdveTdAKe1CRFaYS2MGvOrA/?fmt=auto&%24hq%24=&w=1536
area: og
hide_unavailable: false
tap_action:
  action: navigate
  navigation_path: /config/areas/area/aussen
entities:
  - entity: sensor.temperatur_schlafzimmer_luftfeuchtigkeit
  - entity: sensor.temperatur_schlafzimmer_temperatur
  - entity: scene.ausschalten
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data: {}
      target:
        entity_id: scene.ausschalten
  - entity: scene.kuhlen_22_grad
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data: {}
      target:
        entity_id: scene.kuhlen_22_grad
  - entity: scene.kuhlen_20_grad
    tap_action:
      action: call-service
      service: scene.turn_on
      service_data: {}
      target:
        entity_id: scene.kuhlen_20_grad
```
