### ISSUE TITLE
[Question]: Possibility to change the font color and weight of the card header

### ISSUE THREAD

**Issue by michaelhenningersrb** [junalmeida/homeassistant-minimalistic-area-card#94]
### What happened?

I want to use the card without any background image. I like it plain and white/grey scales.

I am searching for an option to set the title font style ( also the shadow ) somehome. 

![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/18479766/04d66d0c-51de-4747-a733-a79e11ecd32c)

Could you please provide a configuration setting to establish this?

BR Michael

### Card Version

latest

### HomeAssistant Version

latest

**Comment by krom** [comment]
Hi, I have similar issue.
I use background image from area and I want to see dark icons and text on light image and light text ondark image
![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/970843/e495ef08-985b-4f31-8024-4c8eb7fe0181)
For now it's not readable, sorry

**Comment by michaelhenningersrb** [comment]
I got a temporary solution with `card_mod`.
The only problem is that it is not stable on reload. Sometimes the `card_mod` settings do not get displayed:

```yaml
background_color: var(--ha-card-background, var(--card-background-color))  # <-- Sets the background to the default css background color of your theme
card_mod:
  style: |
    .box {
      color: var(--primary-text-color) !important; /** <-- Sets the primary text color **/
      text-shadow: unset !important; /** <-- No text shadow **/
    }
    .box ha-icon-button.state-on state-badge {
      color: black !important; /** <-- Black badge icons **/
    }
    .card-header {
      font-weight: normal !important; /** <-- No bold text **/
    }

```

### Results in:

Light theme:
![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/18479766/0d20e786-52d6-4ae1-9600-4244119c7244)

Dark theme ( i know the badge icon color is bad ):
![image](https://github.com/junalmeida/homeassistant-minimalistic-area-card/assets/18479766/49ff48b5-43d2-4946-86d7-216240d793dd)


My next approach would be to fork this repo to make it stable.

@junalmeida Are you planning to support our wishes in the future? ;)

In the latest release `2024.2.0` there is also an option to configure an icon for an area instead of an image. This would also be nice to configure somewhere:
https://www.home-assistant.io/blog/2024/02/07/release-20242/#icons-everywhere
